export const communities = [
  { id: 'dubai-hills', name: 'Dubai Hills Estate', area: 'Dubai' },
  { id: 'dubai-marina', name: 'Dubai Marina', area: 'Dubai' },
  { id: 'dubai-creek', name: 'Dubai Creek Harbour', area: 'Dubai' },
  { id: 'palm-jumeirah', name: 'Palm Jumeirah', area: 'Dubai' },
  { id: 'downtown', name: 'Downtown Dubai', area: 'Dubai' },
  { id: 'business-bay', name: 'Business Bay', area: 'Dubai' },
  { id: 'jbr', name: 'Jumeirah Beach Residence', area: 'Dubai' },
  { id: 'jvc', name: 'Jumeirah Village Circle', area: 'Dubai' },
  { id: 'jvt', name: 'Jumeirah Village Triangle', area: 'Dubai' },
  { id: 'emirates-hills', name: 'Emirates Hills', area: 'Dubai' },
  { id: 'arabian-ranches', name: 'Arabian Ranches', area: 'Dubai' },
  { id: 'arabian-ranches-2', name: 'Arabian Ranches 2', area: 'Dubai' },
  { id: 'sobha-hartland', name: 'Sobha Hartland', area: 'Dubai' },
  { id: 'sobha-central', name: 'Sobha Central', area: 'Dubai' },
  { id: 'damac-hills', name: 'DAMAC Hills', area: 'Dubai' },
  { id: 'damac-hills-2', name: 'DAMAC Hills 2', area: 'Dubai' },
  { id: 'al-barsha', name: 'Al Barsha', area: 'Dubai' },
  { id: 'al-barsha-south', name: 'Al Barsha South', area: 'Dubai' },
  { id: 'dubai-south', name: 'Dubai South', area: 'Dubai' },
  { id: 'city-walk', name: 'City Walk', area: 'Dubai' },
  { id: 'bluewaters', name: 'Bluewaters Island', area: 'Dubai' },
  { id: 'umm-al-quwain', name: 'Umm Al Quwain', area: 'UAE' },
  { id: 'siniya-island', name: 'Siniya Island', area: 'Umm Al Quwain' },
  { id: 'polo-club', name: 'Grand Polo Club', area: 'Dubai' },
  { id: 'rashid-marina', name: 'Rashid Yachts and Marina', area: 'Dubai' },
  { id: 'meydan', name: 'Meydan', area: 'Dubai' },
  { id: 'tilal-al-ghaf', name: 'Tilal Al Ghaf', area: 'Dubai' },
  { id: 'dubai-land', name: 'Dubai Land', area: 'Dubai' },
];
